//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int Id { get; set; }
        public int BrandId { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> VehicleYear { get; set; }
        public string VinNumber { get; set; }
        public string EngineType { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Models Models { get; set; }
    }
}
